var SELECTORS = {
  first_name: [
    'input[name*="first" i][name*="name" i]',
    'input[id*="first" i][id*="name" i]',
    'input[placeholder*="first name" i]',
    'input[autocomplete="given-name"]',
    'input[data-automation-id*="legalNameSection_firstName"]',
    'input[id*="firstName"]',
    'input[name="firstName"]',
    'input[name="first_name"]',
    'input[id="first_name"]',
  ],
  middle_name: [
    'input[name*="middle" i][name*="name" i]',
    'input[id*="middle" i][id*="name" i]',
    'input[placeholder*="middle name" i]',
    'input[autocomplete="additional-name"]',
    'input[data-automation-id*="middleName"]',
    'input[name="middleName"]',
    'input[name="middle_name"]',
  ],
  last_name: [
    'input[name*="last" i][name*="name" i]',
    'input[id*="last" i][id*="name" i]',
    'input[placeholder*="last name" i]',
    'input[autocomplete="family-name"]',
    'input[data-automation-id*="legalNameSection_lastName"]',
    'input[id*="lastName"]',
    'input[name="lastName"]',
    'input[name="last_name"]',
    'input[id="last_name"]',
  ],
  preferred_name: [
    'input[name*="preferred" i][name*="name" i]',
    'input[id*="preferred" i][id*="name" i]',
    'input[placeholder*="preferred name" i]',
    'input[placeholder*="goes by" i]',
    'input[data-automation-id*="preferredName"]',
    'input[name="preferredName"]',
    'input[name="preferred_name"]',
  ],
  full_name: [
    'input[name*="full" i][name*="name" i]',
    'input[id*="full" i][id*="name" i]',
    'input[placeholder*="full name" i]',
    'input[autocomplete="name"]',
    'input[name="fullName"]',
    'input[name="full_name"]',
    'input[id="fullName"]',
    'input[name="_systemfield_name"]',
    'input[name="name"]',
    'input[id="applicant_name"]',
  ],
  email: [
    'input[type="email"]',
    'input[name*="email" i]',
    'input[id*="email" i]',
    'input[placeholder*="email" i]',
    'input[autocomplete="email"]',
  ],
  phone: [
    'input[type="tel"]',
    'input[name*="phone" i]',
    'input[id*="phone" i]',
    'input[placeholder*="phone" i]',
    'input[autocomplete="tel"]',
    'input[autocomplete="tel-national"]',
    'input[name="CandidatePhone.NormalizedNumber"]',
  ],
  street_address: [
    'input[autocomplete="street-address"]',
    'input[autocomplete="address-line1"]',
    'input[name*="address" i][name*="line" i]',
    'input[name*="street" i]',
    'input[id*="street" i]',
    'input[placeholder*="street address" i]',
    'input[data-automation-id*="addressSection_addressLine1"]',
    'input[name="address1"]',
    'input[name="address_line_1"]',
    'input[id="address_1"]',
    'input[id="resumator-address-value"]',
    'input[id="AddressLine1" i]',
  ],
  city: [
    'input[autocomplete="address-level2"]',
    'input[name*="city" i]',
    'input[id*="city" i]',
    'input[placeholder*="city" i]',
    'input[data-automation-id*="addressSection_city"]',
    'input[id="city" i]',
  ],
  state: [
    'input[autocomplete="address-level1"]',
    'input[name*="state" i]',
    'input[id*="state" i]',
    'input[name*="province" i]',
    'input[id*="province" i]',
    'input[placeholder*="state" i]',
    'input[placeholder*="province" i]',
    'select[name*="state" i]',
    'select[id*="state" i]',
    'select[name*="province" i]',
    'input[data-automation-id*="addressSection_countryRegion"]',
    'select[name="state.value"]',
  ],
  postal_code: [
    'input[autocomplete="postal-code"]',
    'input[name*="postal" i]',
    'input[id*="postal" i]',
    'input[name*="zip" i]',
    'input[id*="zip" i]',
    'input[placeholder*="postal" i]',
    'input[placeholder*="zip" i]',
    'input[data-automation-id*="addressSection_postalCode"]',
    'input[id*="postalCode" i]',
  ],
  country: [
    'input[autocomplete="country-name"]',
    'select[autocomplete="country"]',
    'input[name*="country" i]',
    'select[name*="country" i]',
    'input[id*="country" i]',
    'select[id*="country" i]',
    'input[data-automation-id*="addressSection_countryDropdown"]',
  ],
  linkedin: [
    'input[name*="linkedin" i]',
    'input[id*="linkedin" i]',
    'input[placeholder*="linkedin" i]',
    'input[data-automation-id*="linkedIn"]',
  ],
  github: [
    'input[name*="github" i]',
    'input[id*="github" i]',
    'input[placeholder*="github" i]',
  ],
  portfolio: [
    'input[name*="portfolio" i]',
    'input[id*="portfolio" i]',
    'input[placeholder*="portfolio" i]',
    'input[name*="website" i]',
    'input[id*="website" i]',
    'input[placeholder*="website" i]',
    'input[name*="personal_site" i]',
    'input[autocomplete="url"]',
  ],
  password: [
    'input[type="password"]',
    'input[name*="password" i]',
    'input[id*="password" i]',
    'input[placeholder*="password" i]',
    'input[autocomplete="new-password"]',
    'input[autocomplete="current-password"]',
  ],
  gender: [
    'select[name*="gender" i]',
    'select[id*="gender" i]',
    'select[name*="sex" i]',
    'select[id*="sex" i]',
    'input[name*="gender" i]',
    'input[id*="gender" i]',
  ],
  ethnicity: [
    'select[name*="ethnicity" i]',
    'select[id*="ethnicity" i]',
    'select[name*="race" i]',
    'select[id*="race" i]',
    'select[name*="ethnic" i]',
    'select[id*="ethnic" i]',
  ],
  disability: [
    'select[name*="disability" i]',
    'select[id*="disability" i]',
    'input[name*="disability" i]',
    'input[id*="disability" i]',
  ],
  veteran: [
    'select[name*="veteran" i]',
    'select[id*="veteran" i]',
    'input[name*="veteran" i]',
    'input[id*="veteran" i]',
  ],
  work_authorization: [
    'select[name*="authorized" i]',
    'select[id*="authorized" i]',
    'select[name*="authorization" i]',
    'select[id*="authorization" i]',
    'select[name*="legally" i]',
    'select[id*="legally" i]',
    'select[name*="work_auth" i]',
    'select[id*="work_auth" i]',
  ],
  sponsorship: [
    'select[name*="sponsor" i]',
    'select[id*="sponsor" i]',
    'select[name*="visa" i]',
    'select[id*="visa" i]',
    'select[name*="sponsorship" i]',
    'select[id*="sponsorship" i]',
  ],
};